---
# tasks file for 1_Initial_Setup

- name: 1.1.1 Disable unused filesystem modules
  template: 
    src: module.conf.j2
    dest: "/etc/modprobe.d/{{ item }}.conf"
  loop: "{{ blacklist_fs_modules }}"
  tags:
    - disable_fs_modules
    - setup

- name: 1.1.2 Check if /tmp is not mounted
  command: findmnt -nk /tmp
  register: tmp_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - tmp
    - setup

- name: 1.1.2 Create tmp.mount service if /tmp is not mounted
  template:
    src: tmp.mount.j2
    dest: /etc/systemd/system/tmp.mount
  when: tmp_mount_status.stdout == ''
  tags:
    - tmp
    - setup

- name: 1.1.2 Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: tmp_mount_status.stdout == ''
  tags:
    - tmp
    - setup

- name: 1.1.2 Ensure and start tmp.mount service if not already running
  systemd:
    name: tmp.mount
    state: started
    enabled: yes
  when: tmp_mount_status.stdout == ''
  tags:
    - tmp
    - setup

- name: 1.1.2 Print the status of /tmp mount
  debug:
    msg: "/tmp is {% if tmp_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - tmp
    - setup

- name: 1.1.3 Check if /var is not mounted
  command: findmnt -nk /var
  register: var_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - var
    - setup

- name: 1.1.3 Print the status of /var mount 
  debug:
    msg: "/var is {% if var_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - var
    - setup

- name: 1.1.4 Check if /var/tmp is not mounted
  command: findmnt -nk /var/tmp
  register: var_tmp_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - var_tmp
    - setup

- name: 1.1.4 Print the status of /var/tmp mount
  debug:
    msg: "/var/tmp is {% if var_tmp_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - var_tmp
    - setup

- name: 1.1.5 Check if /var/log is not mounted
  command: findmnt -nk /var/log
  register: var_log_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - var_log
    - setup

- name: 1.1.5 Print the status of /var/log mount
  debug:
    msg: "/var/log is {% if var_log_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - var_log
    - setup

- name: 1.1.6 Check if /var/log/audit is not mounted
  command: findmnt -nk /var/log/audit
  register: var_log_audit_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - var_log_audot
    - setup

- name: 1.1.6 Print the status of /var/log/audit mount
  debug:
    msg: "/var/log/audit is {% if var_log_audit_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - var_log_audit
    - setup

- name: 1.1.7 Check if /home is not mounted
  command: findmnt -nk /home
  register: home_mount_status
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - home
    - setup

- name: 1.1.7 Print the status of /home mount
  debug:
    msg: "/home is {% if home_mount_status.stdout == '' %}not mounted{% else %}mounted{% endif %}."
  tags:
    - home
    - setup

- name: 1.1.8 Check if /dev/shm exists in /etc/fstab
  command: grep '/dev/shm' /etc/fstab
  register: dev_shm_option
  failed_when: false
  changed_when: false
  check_mode: no
  tags:
    - shm
    - setup

- name: 1.1.8 Print the status of /dev/shm option
  debug:
    msg: "/dev/shm is {% if dev_shm_option.stdout == '' %}not configured{% else %}configured{% endif %} in /etc/fstab."
  tags:
    - shm
    - setup

- name: 1.1.8 Configure and mount /dev/shm
  mount:
    src: tmpfs
    fstype: tmpfs
    name: /dev/shm
    opts: defaults,rw,nosuid,nodev,noexec,relatime,size={{ shm_size }}
    state: mounted 
  when: dev_shm_option.stdout == ''
  tags:
    - shm
    - setup

- name: 1.1.9 Disable and mask autofs service
  systemd:
    name: autofs
    enabled: no
    masked: true
  tags:
    - autofs
    - setup

- name: 1.5.1 Ensure prelink is not installed
  apt:
    name: prelink
    state: absent
  tags:
    - prelink
    - setup

- name: 1.5.2 Ensure address space layout randomization (ASLR) is enabled
  sysctl:
    state: present
    name: kernel.randomize_va_space
    value: "2"
    reload: true
    sysctl_set: true
  tags:
    - sysctl
    - setup

- name: 1.5.3 Ensure ptrace_scope is restricted
  sysctl:
    state: present
    name: kernel.yama.ptrace_scope
    value: "1"
    reload: true
    sysctl_set: true
  tags:
    - sysctl
    - setup

- name: 1.5.4 Ensure automatic error reporting is not enabled
  apt:
    name: apport
    state: absent
  tags:
    - apport
    - setup

- name: 1.5.5 Ensure core dumps are restricted
  sysctl:
    state: present
    name: fs.suid_dumpable
    value: "0"
    reload: true
    sysctl_set: true
  tags:
    - sysctl
    - setup


